"""The sim-side joint contract shared with the hardware stack (diogenes_control).

For every actuated joint it records the MJCF range and, as plain signs, which way
a POSITIVE joint angle moves that leg's foot. The hardware stack's per-joint
`direction` signs were verified by hand against exactly these meanings, so the
contract carries a `direction_signature` (a hash over the joint names and those
signs). The control code refuses to apply gain when the signature it was
verified against differs from the contract it is given.

Only signs are hashed, not magnitudes, so a CAD tweak that moves a foot a few mm
leaves the signature alone, while a flipped joint axis or a renamed joint
changes it. Ranges are recorded (the control code derives its limits from
them) but deliberately kept out of the signature: a new range does not
invalidate a direction check.

Needs only mujoco, so it also runs outside the mjlab environment:

  python src/diogenes_mjlab/harold_biped/joint_contract.py \\
      --out ../diogenes_control/sim_joint_contract.json

tests/test_joint_contract.py pins the output against a golden file.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import mujoco
import numpy as np

XML_PATH = Path(__file__).parent / "xmls" / "scene.xml"
ROOT_BODY_NAME = "body_assy"

# Joint -> the foot site it moves, in XML (== policy) order.
JOINT_FOOT: dict[str, str] = {
  "left_hip": "left_foot",
  "left_thigh": "left_foot",
  "left_calf": "left_foot",
  "right_hip": "right_foot",
  "right_thigh": "right_foot",
  "right_calf": "right_foot",
}

# Axes of the exported body_assy frame (see harold_biped_constants.py).
FRAME_AXES = ("left", "back", "up")
PROBE_RAD = 0.1
# A displacement component counts if it is at least this fraction of the total.
SIGN_THRESHOLD = 0.25


def build_model() -> mujoco.MjModel:
  """The suspended (fixed-base) model in the exported frame."""
  spec = mujoco.MjSpec.from_file(str(XML_PATH))
  root = spec.body(ROOT_BODY_NAME)
  for joint in list(root.joints):
    spec.delete(joint)
  return spec.compile()


def positive_motion(model: mujoco.MjModel, joint: str, foot: str) -> dict[str, int]:
  """Signs of the foot's displacement, in the base frame, for +PROBE_RAD at the zero pose."""
  data = mujoco.MjData(model)

  def foot_in_base() -> np.ndarray:
    mujoco.mj_kinematics(model, data)
    base = data.body(ROOT_BODY_NAME)
    return base.xmat.reshape(3, 3).T @ (data.site(foot).xpos - base.xpos)

  start = foot_in_base()
  data.qpos[model.joint(joint).qposadr[0]] = PROBE_RAD
  delta = foot_in_base() - start
  norm = np.linalg.norm(delta)
  return {
    axis: int(np.sign(c)) if abs(c) >= SIGN_THRESHOLD * norm else 0
    for axis, c in zip(FRAME_AXES, delta)
  }


def direction_signature(joints: dict[str, dict]) -> str:
  payload = json.dumps(
    [[name, spec["positive_moves_foot"]] for name, spec in joints.items()],
    sort_keys=True,
  )
  return hashlib.sha256(payload.encode()).hexdigest()[:16]


def build_contract() -> dict:
  model = build_model()
  joints = {}
  for name, foot in JOINT_FOOT.items():
    lo, hi = model.jnt_range[model.joint(name).id]
    joints[name] = {
      "range": [round(float(lo), 6), round(float(hi), 6)],
      "foot": foot,
      "positive_moves_foot": positive_motion(model, name, foot),
    }
  return {
    "_comment": (
      "Generated by diogenes_mjlab/src/diogenes_mjlab/harold_biped/joint_contract.py "
      "from harold_biped.xml. Do not edit by hand; regenerate."
    ),
    "frame": "body_assy exported frame: +x robot left, +y robot back, +z up",
    "joints": joints,
    "direction_signature": direction_signature(joints),
  }


def dumps(contract: dict) -> str:
  return json.dumps(contract, indent=2) + "\n"


def main() -> None:
  parser = argparse.ArgumentParser(description="Export the Harold sim joint contract.")
  parser.add_argument("--out", type=Path, action="append",
                      help="Write here (repeatable). Omit to print.")
  args = parser.parse_args()
  text = dumps(build_contract())
  if not args.out:
    print(text, end="")
  for path in args.out or []:
    path.write_text(text)
    print(f"wrote {path}")


if __name__ == "__main__":
  main()
